sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule==1.25
  - pip install ansible
  - pip install docker
  - pip install testinfra==1.6.4
script:
  - molecule test
